---
- name: 'Test'
  hosts: all
  become: yes

  tasks:
    - import_role:
        name: common

- name: 'install webserver'
  hosts: srv1
  become: yes

  tasks:
    - import_role:
        name: apache
